# Generated by Django 5.2.15 on 2026-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aifilejob_docs_creation_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('web_recording', 'Web recording'), ('web_file_upload', 'Web file upload'), ('mobile_recording', 'Mobile recording'), ('mobile_file_upload', 'Mobile file upload'), ('imported_transcript', 'Imported transcript')], default='unknown', max_length=25),
        ),
    ]
